version: '3.4'

services:
  productstockwebservice:
    image: productstockwebservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

  mysql:
    image: mysql:5.7 
    container_name: products_mysql
    command: mysqld --user=root
    volumes:
      - ./migrations/create_product_tables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=products
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
